### ISSUE TITLE
[Crash]: Crash on startup

### ISSUE THREAD

**Issue by SplendidAlakey** [Fuzss/mindfuldarkness#6]
### Mod Loader (Required)

Quilt

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.4

### Notes (Required)

The game crashes immediately on startup on Quilt. ~~This is probably related to the fix done for #5.~~ ~~It isn't, 4.0.3 works.~~ While it doesn't crash on startup, still might be related, see comment below.

### Crash Report (Required)

https://gist.github.com/SplendidAlakey/dcbb091232d9fd049d8a5e77658d6e9e#file-crash-log

### latest.log (Optional)

https://gist.github.com/SplendidAlakey/dcbb091232d9fd049d8a5e77658d6e9e#file-latest-log

**Comment by SplendidAlakey** [comment]
I'm actually crashing on both Fabric and Quilt with 4.0.3, too, if some texture packs are present (not sure which ones, yet). Fabric continuously reloads resources, whereas Quilt just crashes. Here's a part of the log, I'll get the full one later, with the reproduction steps, if needed.
```
[12:20:39] [Render thread/ERROR]: Couldn't load filter metadata
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Expected name at line 5 column 4 path $.pack.pack_format
	at net.minecraft.class_3518.method_15267(class_3518.java:512) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3518.method_15274(class_3518.java:562) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3518.method_15255(class_3518.java:570) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3255.method_14392(class_3255.java:74) [transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3255.method_14407(class_3255.java:66) [transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_6861.method_41274(class_6861.java:65) [transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_6861.<init>(class_6861.java:34) [transformed-mod-minecraft-v1.19.2.jar:?]
	at fuzs.mindfuldarkness.client.packs.resources.ColorChangingResourceManager.<init>(ColorChangingResourceManager.java:33) [transformed-mod-mindfuldarkness.i0:0/:?]
	at net.minecraft.class_3304.handler$lof000$mindfuldarkness$createReload(class_3304.java:2531) [transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3304.method_18232(class_3304.java:47) [transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:648) [transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:205) [transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [transformed-mod-minecraft-v1.19.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:527) [quilt-loader-0.19.0-beta.13.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) [quilt-loader-0.19.0-beta.13.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) [quilt-loader-0.19.0-beta.13.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 5 column 4 path $.pack.pack_format
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[gson-2.8.9.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:504) ~[gson-2.8.9.jar:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:413) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:683) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:684) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:866) ~[gson-2.8.9.jar:?]
	at net.minecraft.class_3518.method_15267(class_3518.java:510) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	... 22 more
```

**Comment by Fuzss** [comment]
The Fabric crash would be great to have.

**Comment by SplendidAlakey** [comment]
Sorry, I seemed to have rushed to conclusions there. Fabric got stuck in an infinite reload loop, but I can't reproduce it, so it must've been a one-off. Right now Fabric seems to work fine, Quilt crashes on 4.0.3, if some resource packs are present (still figuring out which) and 4.0.4 just outright crashes on startup with just Mindful Darkness.

**Comment by Fuzss** [comment]
Any issues regarding this with v4.0.5?
